-- TRỐN SẾP TAN CA — SUPABASE LEADERBOARD
-- Chạy toàn bộ file này trong Supabase SQL Editor.

create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  player_id text not null,
  nickname text not null,
  level integer not null check (level between 1 and 200),
  time_ms integer not null check (time_ms between 2000 and 900000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (player_id, level)
);

create index if not exists leaderboard_level_time_idx
  on public.leaderboard (level, time_ms);

alter table public.leaderboard enable row level security;

drop policy if exists "Public can read leaderboard" on public.leaderboard;
create policy "Public can read leaderboard"
  on public.leaderboard
  for select
  to anon, authenticated
  using (true);

-- Không tạo policy INSERT/UPDATE cho client.
-- api/leaderboard.js dùng SUPABASE_SERVICE_ROLE_KEY ở server để ghi điểm.

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'leaderboard'
  ) then
    alter publication supabase_realtime add table public.leaderboard;
  end if;
end $$;
